version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: postgres-integration-test
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb-test:
    image: mongo:7.0
    container_name: mongodb-integration-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
      MONGO_INITDB_DATABASE: testprojectsdb
    ports:
      - "27018:27017"

volumes:
  postgres_test_data:
  mongo_test_data: